### ISSUE TITLE
A lot of content is now provider locked.

### ISSUE THREAD

**Issue by slices81** [moneymaker365/plugin.video.ustvvod#16]
Ideal would be to add another tab to the settings for login information, and show the locked episodes.
Not sure if this is possible, I've been trying to get this to work with comcast. I can do the login and pass the response back to adobe. Next step is to get the token back from adbobe.  Theoretically we could do this the same way as the android app, but need to know how they generate the parameters they send. Have decompiled an app to see if I can spot this.

**Comment by bradyemerson** [comment]
Would you consider providing an option to use chrome launcher (https://github.com/AddonScriptorDE/plugin.program.chrome.launcher/) as an alternative to play vendor locked content? Clearly not as ideal as playing video within Kodi, but would be nice to still have access to additional content in some form while options to play within Kodi are explored.

Also, it would be cool if a chrome launcher option appeared in a yes/no dialog as a fallback if resolving the video URL failed, even for known sources, since things change occasionally and shows/sources break.  Something like: "Loading failed. Try to play this URL in Chrome?" Yes/No

**Comment by alexdunlop81** [comment]
There may be a better solution if we need to restort to using chrome which would still allow playback in kodi. As for using chrome launcher as a fallback, we probbably have more problems with navigation than we do with playback.

Plus I can't use it on my pivos box.

**Comment by frostyon420** [comment]
man its been three months since i last checked on this plugin, are you guys any closer to adding provider locked content?

**Comment by slices81** [comment]
Not much, we have a better understanding of what we don't know, seems the private key is account specific which means it must be passed back from adbobe on login. Needs more work to se if we can duplicate the encryption with any of the returned dara.

**Comment by frostyon420** [comment]
Well, cheers to you guys doing the hard stuff :)

**Comment by zymbiosis** [comment]
FYI, I've been looking at the NBC sports Live Extra plugin (https://github.com/eracknaphobia/plugin.video.nbcsnliveextra) and notice they have authentication with a couple providers and have managed to get the adobe auth fully working.  Perhaps this could be of some help.  I'd be willing to help out as well but currently am focusing on getting some of the networks back working that I'd like to watch.  One thing to note is that plugin wont seem to work if you're using Google or OpenDNS servers until adobe fixes their redirect to a .app tld.

**Comment by slices81** [comment]
Yes  should be a good chance this will work for the nbcu networks, and maybe a few others. Struggling for time though.

**Comment by zymbiosis** [comment]
No problem.  I did manage to get a couple of the other networks sorted out (or, at least the parts that needed to be fixed in this plugin.  Other parts for kodi are fixed in 15.2 rc1).  I may have time to look at this.
